
# ------------------- Build configuration

DOCKER_IMAGE := ghcr.io/ezcluster/tower

VERSION := 0.1.0

DOCKER_TAG := $(VERSION)

BUILDX_CACHE=/tmp/docker_cache

# You can switch between simple (faster) docker build or multiplatform one.
# For multiplatform build on a fresh system, do 'make docker-set-multiplatform-builder'
#DOCKER_BUILD := docker buildx build --builder multiplatform --cache-to type=local,dest=$(BUILDX_CACHE),mode=max --cache-from type=local,src=$(BUILDX_CACHE) --platform linux/amd64,linux/arm64
DOCKER_BUILD := docker build

# Comment this to just build locally
DOCKER_PUSH := --push

# To authenticate for pushing in github repo:
# echo $GITHUB_TOKEN | docker login ghcr.io -u $USER_NAME --password-stdin


.PHONY: help
help: ## Display this help.
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n"} /^[a-zA-Z_0-9-]+:.*?##/ { printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)

version: ## Adjust version
	@echo "// Generated by Makefile\n\npackage cmd\n\nvar version = \"$(VERSION)\"\n" >cmd/version_.go

.PHONY: docker
docker: ## Build and push tower imahe
	$(DOCKER_BUILD) ${DOCKER_PUSH}  -t $(DOCKER_IMAGE):$(DOCKER_TAG) -f ./docker/Dockerfile .

# ----------------------------------------------------------------------Docker local config

.PHONY: docker-set-multiplatform-builder
docker-set-multiplatform-builder:  ## TO EXECUTE ONCE ON build system, to allow multiplatform build with cache
	docker buildx create --name multiplatform --driver docker-container
